---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---

## Peer-reviewed
Perez-Corona, Y.^\*^, Torres, H., & **Ramos-Musalem, K.** (2026). Detection and Characterization of Mesoscale Eddies in the Gulf of California Using High-Resolution Satellite Altimetry. *Remote Sensing*, 18(3), 434. DOI: [10.3390/rs18030434](https://doi.org/10.3390/rs18030434)

Moreles, E., Romero, E., **Ramos-Musalem, K.**, & Tenorio-Fernandez, L. (2025). The global ocean mixed layer depth derived from an energy approach. *Ocean Science*, Vol. 21, Issue 5, 2019–2039. DOI: [10.5194/os-21-2019-2025](https://doi.org/10.5194/os-21-2019-2025)

**Ramos-Musalem, K.**, Gille, S. T., Cornuelle, B. D., & Mazloff, M. R. (2023). High-frequency variability induced in the Southern California Bight by a wind event in Sebastián Vizcaíno Bay, Baja California. *Journal of Geophysical Research: Oceans*, e2022JC019547. DOI:[10.1029/2022JC019547](https://doi.org/10.1029/2022JC019547).

Burgos-Cuevas, A., Ruiz-Angulo, A., Morales, C. A. P., **Ramos-Musalem, K.**, & Molina, C. D. G. (2022). Experimental downslope gravity currents over a synthetic topography. *Atmósfera*. DOI:[10.20937/ATM.53156](https://doi.org/10.20937/ATM.53156)

Saldías, G. S., **Ramos-Musalem, K.**, & Allen, S. E. (2021). Circulation and upwelling induced by coastal trapped waves over a submarine canyon in an idealized eastern boundary margin. *Geophysical Research Letters*, 48(11), e2021GL093548. DOI:[10.1029/2021GL093548](https://doi.org/10.1029/2021GL093548)

**Ramos-Musalem, K.** & Allen, S. E. (2020). The impact of initial tracer profile on the exchange and on-shelf distribution of tracers induced by a submarine canyon. *Journal of Geophysical Research: Oceans*, 125(3), e2019JC015785. DOI:[10.1029/2019JC015785](https://doi.org/10.1029/2019JC015785)

**Ramos-Musalem, K.** & Allen, S. E. (2019). The impact of locally enhanced vertical diffusivity on the cross-shelf transport of tracers induced by a submarine canyon. *Journal of Physical Oceanography*, 49(2), 561–584. DOI: [10.1175/JPO-D-18-0174.1](https://doi.org/10.1175/JPO-D-18-0174.1)

Arane, T., **Musalem, A. K. R**., & Fridman, M. (2009). Coupling between two singing wineglasses. *American Journal of Physics*, 77(11), 1066–1067. DOI: [10.1119/1.3119175](https://doi.org/10.1119/1.3119175)

\* PhD student

## Academic writing

PhD Thesis: Transport through submarine canyons (2020). University of British Columbia. [link](https://open.library.ubc.ca/collections/ubctheses/24/items/1.0388506)

BSc Thesis: Estudio numérico de los forzamientos que generan la surgencia de Yucatán (2013). UNAM, Mexico, 77. (In Spanish) [link](https://hdl.handle.net/20.500.14330/TES01000692102)
